# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T16:58:22+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Path, Query

from models import AspectId

app = MCPProxy(
    description="BC Laws is an electronic library providing free public access to the laws of British Columbia. BC Laws is hosted by the Queen's Printer of British Columbia and published in partnership with the Ministry of Justice and the Law Clerk of the Legislative Assembly.BC Laws contains a comprehensive collection of BC legislation and related materials. It is available on the internet in two forms:First: The library is available as a web site in which users can browse and search the laws of British Columbia.Second: The library is available as a portal to legislation in raw XML data format, accessible via the BC Laws API2. This direct access to raw data is intended to enable third parties to build or add their own custom applications based on the structure of the data and all the associated search functionality inherent in that structure. The BC Laws website itself is an example of one such application. \n\nPlease note that you may experience issues when submitting requests to the delivery or test environment if using this [OpenAPI specification](https://github.com/bcgov/api-specs) in other API console viewers.",
    license={
        'name': "Queen's Printer License",
        'url': 'http://www.bclaws.ca/standards/2014/QP-License_1.0.html',
    },
    termsOfService='http://www2.gov.bc.ca/gov/content?id=D1EE0A405E584363B205CD4353E02C88',
    title='BC Laws',
    version='1.0.0',
    servers=[
        {'url': 'http://www.bclaws.ca/civix'},
        {'url': 'https://www.bclaws.ca/civix'},
    ],
)


@app.get('/content/{aspectId}', tags=['bclaws_metadata_extraction'])
def get_content__aspect_id(aspect_id: AspectId = Path(..., alias='aspectId')):
    """
    Describes the documents and directories available within a specific 'aspect' (content group) of the BCLaws library
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/content/{aspectId}/{civixDocumentId}', tags=['bclaws_metadata_extraction'])
def get_content__aspect_id__civix_document_id(
    aspect_id: AspectId = Path(..., alias='aspectId'),
    civix_document_id: str = Path(..., alias='civixDocumentId'),
):
    """
    Lists the metadata available for the specified index or directory from the BCLaws legislative respository
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/document/id/{aspectId}/{civixIndexId}/{civixDocumentId}',
    description=""" The /document API allows you to retrieve actual documents from the BCLaws legislative repository. To retrieve a document from the repository you need the aspect identifier and two other specific pieces of information about the document: the index identifier and the document identifier. These unique identifiers can be retrieved from the /content API. """,
    tags=['bclaws_document_retrieval'],
)
def get_document_id__aspect_id__civix_index_id__civix_document_id(
    aspect_id: AspectId = Path(..., alias='aspectId'),
    civix_index_id: str = Path(..., alias='civixIndexId'),
    civix_document_id: str = Path(..., alias='civixDocumentId'),
):
    """
    Retrieves a specific document from the BCLaws legislative repository (HTML format)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/document/id/{aspectId}/{civixIndexId}/{civixDocumentId}/search/{searchString}',
    description=""" The /document API allows you to retrieve actual documents from the BCLaws legislative repository. To retrieve a document from the repository you need the aspect identifier and two other specific pieces of information about the document: the index identifier and the document identifier. These unique identifiers can be retrieved from the /content API. """,
    tags=['bclaws_document_retrieval', 'bclaws_highlighted_document_search'],
)
def retrieve_highlighted_document_bclaws(
    aspect_id: AspectId = Path(..., alias='aspectId'),
    civix_index_id: str = Path(..., alias='civixIndexId'),
    civix_document_id: str = Path(..., alias='civixDocumentId'),
    search_string: str = Path(..., alias='searchString'),
):
    """
    Retrieves a specific document from the BCLaws legislative repository with search text highlighted (HTML format)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/document/id/{aspectId}/{civixIndexId}/{civixDocumentId}/xml',
    description=""" The /document API allows you to retrieve actual documents from the BCLaws legislative repository. To retrieve a document from the repository you need the aspect identifier and two other specific pieces of information about the document: the index identifier and the document identifier. These unique identifiers can be retrieved from the /content API. """,
    tags=['bclaws_document_retrieval'],
)
def retrieve_bclaws_document_xml(
    aspect_id: AspectId = Path(..., alias='aspectId'),
    civix_index_id: str = Path(..., alias='civixIndexId'),
    civix_document_id: str = Path(..., alias='civixDocumentId'),
):
    """
    Retrieves a specific document from the BCLaws legislative repository (XML format)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/document/id/{aspectId}/{civixIndexId}/{civixDocumentId}/xml/search/{searchString}',
    description=""" The /document API allows you to retrieve actual documents from the BCLaws legislative repository. To retrieve a document from the repository you need the aspect identifier and two other specific pieces of information about the document: the index identifier and the document identifier. These unique identifiers can be retrieved from the /content API. """,
    tags=['bclaws_document_retrieval', 'bclaws_highlighted_document_search'],
)
def retrieve_highlighted_document_from_bclaws(
    aspect_id: AspectId = Path(..., alias='aspectId'),
    civix_index_id: str = Path(..., alias='civixIndexId'),
    civix_document_id: str = Path(..., alias='civixDocumentId'),
    search_string: str = Path(..., alias='searchString'),
):
    """
    Retrieves a specific document from the BCLaws legislative repository with search text highlighted (XML format)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/search/{aspectId}/fullsearch',
    tags=['bclaws_metadata_extraction', 'bclaws_document_retrieval'],
)
def get_search__aspect_id_fullsearch(
    aspect_id: AspectId = Path(..., alias='aspectId'),
    q: str = 'water',
    s: str = '0',
    e: int = 20,
    n_frag: int = Query(..., alias='nFrag'),
    l_frag: int = Query(..., alias='lFrag'),
):
    """
    A listing of metadata available for the specified aspect and search term from the BCLaws legislative repository
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
