# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T16:58:22+00:00

from __future__ import annotations

from enum import Enum


class AspectId(Enum):
    complete = 'complete'
    corpreg = 'corpreg'
    bcgaz1 = 'bcgaz1'
    bcgaz2 = 'bcgaz2'
    oic = 'oic'
    psl = 'psl'
    ecb = 'ecb'
    hscr = 'hscr'
    arch_oic = 'arch_oic'
